In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("DateFruit_Dataset.csv")

In [3]:
data.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [4]:
data.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [5]:
data.shape

(898, 35)

In [6]:
X=data.drop("Class",axis=1)
y=data["Class"]

In [7]:
X.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,0.6019,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,0.4134,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,0.9183,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,1.8028,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,0.8865,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666

In [8]:
y.head()

0    BERHI
1    BERHI
2    BERHI
3    BERHI
4    BERHI
Name: Class, dtype: str

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

y=le.fit_transform(y)

In [10]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

X_train_scaled=sc.fit_transform(X_train)
X_test_scaled=sc.transform(X_test)

In [12]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch .utils.data import TensorDataset,DataLoader

In [19]:
X_train_tensor=torch.tensor(X_train_scaled, dtype=torch.float32)
X_test_tensor=torch.tensor(X_test_scaled, dtype=torch.float32)

y_train_tensor=torch.tensor(y_train, dtype=torch.long)
y_test_tensor=torch.tensor(y_test, dtype=torch.long)

In [20]:
train_dataset=TensorDataset(X_train_tensor,y_train_tensor)
test_dataset=TensorDataset(X_test_tensor,y_test_tensor)

In [21]:
train_dataloader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_dataloader=DataLoader(test_dataset,batch_size=32)

In [22]:
#build our model architecture
class Ann(nn.Module):
    def __init__(self):
        super(Ann,self).__init__()
        
        self.model=nn.Sequential(
            #Input Layer
            nn.Linear(X_train.shape[1],64),
            nn.ReLU(),
            
            #Hidden layer
            nn.Linear(64,64),
            nn.ReLU(),
            
            #Output Layer
            nn.Linear(64,7),
        )
    def forward(self,x):
        return  self.model(x)

In [23]:

model=Ann()

#loss and optim
criteria=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters())

In [24]:
#training model
epoches=100

for epoch in range(epoches):
    model.train()
    running_loss=0.0

    for xb,yb in train_dataloader:
        optimizer.zero_grad()

        outputs=model(xb)
        loss=criteria(outputs,yb)
        loss.backward()
        optimizer.step()

        running_loss+=loss.item()

    epoch_training_loss=running_loss/len(train_dataloader)

    print("Epoches:",epoch+1,"/",epoches,"====> Training Loss:",epoch_training_loss)

Epoches: 1 / 100 ====> Training Loss: 1.7096643240555474
Epoches: 2 / 100 ====> Training Loss: 1.1109767582105554
Epoches: 3 / 100 ====> Training Loss: 0.7183359472647958
Epoches: 4 / 100 ====> Training Loss: 0.5446963064048601
Epoches: 5 / 100 ====> Training Loss: 0.4487639238005099
Epoches: 6 / 100 ====> Training Loss: 0.382400653284529
Epoches: 7 / 100 ====> Training Loss: 0.33850836300331616
Epoches: 8 / 100 ====> Training Loss: 0.2995073581519334
Epoches: 9 / 100 ====> Training Loss: 0.2830503029019936
Epoches: 10 / 100 ====> Training Loss: 0.2557358178107635
Epoches: 11 / 100 ====> Training Loss: 0.24054350444804068
Epoches: 12 / 100 ====> Training Loss: 0.22889094540606375
Epoches: 13 / 100 ====> Training Loss: 0.21905155188363531
Epoches: 14 / 100 ====> Training Loss: 0.20392267802811187
Epoches: 15 / 100 ====> Training Loss: 0.1957718292656152
Epoches: 16 / 100 ====> Training Loss: 0.1847929821714111
Epoches: 17 / 100 ====> Training Loss: 0.17812062427401543
Epoches: 18 / 100 ====> Training Loss: 0.17471580466498499
Epoches: 19 / 100 ====> Training Loss: 0.16748927468838898
Epoches: 20 / 100 ====> Training Loss: 0.1532633191217547
Epoches: 21 / 100 ====> Training Loss: 0.1536631750995698
Epoches: 22 / 100 ====> Training Loss: 0.14696691784521806
Epoches: 23 / 100 ====> Training Loss: 0.13572612404823303
Epoches: 24 / 100 ====> Training Loss: 0.1380801871418953
Epoches: 25 / 100 ====> Training Loss: 0.12806338638715123
Epoches: 26 / 100 ====> Training Loss: 0.12726253846093363
Epoches: 27 / 100 ====> Training Loss: 0.12092851725933344
Epoches: 28 / 100 ====> Training Loss: 0.12041027568604636
Epoches: 29 / 100 ====> Training Loss: 0.12130957679904025
Epoches: 30 / 100 ====> Training Loss: 0.1173749036439087
Epoches: 31 / 100 ====> Training Loss: 0.11415614900381668
Epoches: 32 / 100 ====> Training Loss: 0.11137838856033656
Epoches: 33 / 100 ====> Training Loss: 0.10674441771824723
Epoches: 34 / 100 ====> Training Loss: 0.10672127941380376
Epoches: 35 / 100 ====> Training Loss: 0.10437970316928366
Epoches: 36 / 100 ====> Training Loss: 0.09767616880328758
Epoches: 37 / 100 ====> Training Loss: 0.10240954014918079
Epoches: 38 / 100 ====> Training Loss: 0.10111705821169459
Epoches: 39 / 100 ====> Training Loss: 0.10306998836281507
Epoches: 40 / 100 ====> Training Loss: 0.09870656846981982
Epoches: 41 / 100 ====> Training Loss: 0.08904172852635384
Epoches: 42 / 100 ====> Training Loss: 0.08966797541664995
Epoches: 43 / 100 ====> Training Loss: 0.08457087757794754
Epoches: 44 / 100 ====> Training Loss: 0.08485412472130163
Epoches: 45 / 100 ====> Training Loss: 0.08285382276643878
Epoches: 46 / 100 ====> Training Loss: 0.08584587316474189
Epoches: 47 / 100 ====> Training Loss: 0.07828729862914137
Epoches: 48 / 100 ====> Training Loss: 0.0783751180962376
Epoches: 49 / 100 ====> Training Loss: 0.07564592029413451
Epoches: 50 / 100 ====> Training Loss: 0.07962723371937223
Epoches: 51 / 100 ====> Training Loss: 0.06964147173921051
Epoches: 52 / 100 ====> Training Loss: 0.0729971455572092
Epoches: 53 / 100 ====> Training Loss: 0.07161163554891296
Epoches: 54 / 100 ====> Training Loss: 0.0729273319568323
Epoches: 55 / 100 ====> Training Loss: 0.06173566755150323
Epoches: 56 / 100 ====> Training Loss: 0.07368392096427472
Epoches: 57 / 100 ====> Training Loss: 0.07637020475838495
Epoches: 58 / 100 ====> Training Loss: 0.06274715102399173
Epoches: 59 / 100 ====> Training Loss: 0.06905213298033112
Epoches: 60 / 100 ====> Training Loss: 0.06663375299261964
Epoches: 61 / 100 ====> Training Loss: 0.06546441710594555
Epoches: 62 / 100 ====> Training Loss: 0.06378662080058585
Epoches: 63 / 100 ====> Training Loss: 0.060350743810767715
Epoches: 64 / 100 ====> Training Loss: 0.06307657878926914
Epoches: 65 / 100 ====> Training Loss: 0.05727925932075342
Epoches: 66 / 100 ====> Training Loss: 0.059664378833511604
Epoches: 67 / 100 ====> Training Loss: 0.05819287940697825
Epoches: 68 / 100 ====> Training Loss: 0.05625665204032608
Epoches: 69 / 100 ====> Training Loss: 0.06214782842637404
Epoches: 70 / 100 ====> Training Loss: 0.050732626903640186
Epoches: 71 / 100 ====> Training Loss: 0.049618339489983475
Epoches: 72 / 100 ====> Training Loss: 0.04934764884250319
Epoches: 73 / 100 ====> Training Loss: 0.049886079849270376
Epoches: 74 / 100 ====> Training Loss: 0.05924327238260404
Epoches: 75 / 100 ====> Training Loss: 0.047769545435743486
Epoches: 76 / 100 ====> Training Loss: 0.04715205858583036
Epoches: 77 / 100 ====> Training Loss: 0.05087816401425263
Epoches: 78 / 100 ====> Training Loss: 0.04959525132511297
Epoches: 79 / 100 ====> Training Loss: 0.04415336141929678
Epoches: 80 / 100 ====> Training Loss: 0.05482743969996986
Epoches: 81 / 100 ====> Training Loss: 0.04770402634597343
Epoches: 82 / 100 ====> Training Loss: 0.041173715954241547
Epoches: 83 / 100 ====> Training Loss: 0.04167603964552931
Epoches: 84 / 100 ====> Training Loss: 0.03573649234401629
Epoches: 85 / 100 ====> Training Loss: 0.038903814831586635
Epoches: 86 / 100 ====> Training Loss: 0.03804579976460208
Epoches: 87 / 100 ====> Training Loss: 0.038486304682800954
Epoches: 88 / 100 ====> Training Loss: 0.035191641877526825
Epoches: 89 / 100 ====> Training Loss: 0.03552012475531386
Epoches: 90 / 100 ====> Training Loss: 0.03719182893552858
Epoches: 91 / 100 ====> Training Loss: 0.03457492877445791
Epoches: 92 / 100 ====> Training Loss: 0.03135256364475936
Epoches: 93 / 100 ====> Training Loss: 0.03340717668280653
Epoches: 94 / 100 ====> Training Loss: 0.030136141379404326
Epoches: 95 / 100 ====> Training Loss: 0.033038061532272914
Epoches: 96 / 100 ====> Training Loss: 0.03706979786005357
Epoches: 97 / 100 ====> Training Loss: 0.028947496781652066
Epoches: 98 / 100 ====> Training Loss: 0.02620041775314704
Epoches: 99 / 100 ====> Training Loss: 0.03022483934688827
Epoches: 100 / 100 ====> Training Loss: 0.02739351869398809

In [33]:
#Evaluation
model.eval()

correct=0
total=0

with torch.no_grad():
    for xb,yb in test_dataloader:
        outputs=model(xb)
        _,predicted=torch.max(outputs,1)

        correct+=(predicted==yb).sum().item()
        total=y_test.shape[0]

print("Accuracy:",correct/total*100)

Accuracy: 95.55555555555556